name: gourmet_search
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  dio: ^5.9.1
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  google_maps_flutter: ^2.14.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg"

flutter_native_splash:
  color: "f1e0e5" 
  
  image: "assets/splash/app_splash.jpg"
  
  android_12:
    image: "assets/splash/app_splash.jpg"
    icon_background_color: "f1e0e5"
    
  fullscreen: true